name: E2E

on: push

jobs:
  Build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        node-version: [10.x, 12.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - run: |
          npm ci
          npm i -g azure-functions-core-tools@3 --unsafe-perm true
          npm run build
        env:
          CI: 1

      - name: Save dist folders
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  E2E:
    needs: Build
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        node-version: [10.x, 12.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download built folders ⏬
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CI: 1
        with:
          command: npm run e2e

  Artifacts:
    needs: E2E
    runs-on: ubuntu-16.04
    name: Artifacts
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
