name: E2E

on: push

jobs:
  Build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        node-version: [10.x, 12.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - run: |
          npm ci
          npm run build
        env:
          CI: 1

      - name: Save dist folders
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  E2E:
    needs: Build
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        node-version: [10.x, 12.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download built folders ⏬
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CI: 1
        with:
          command: |
            npm i -g azure-functions-core-tools@3 --unsafe-perm true
            npm run e2e
